version: '3.8'
services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: saas
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: plataforma          # Banco de dados inicial
    volumes:
      - ./db/init.sh  # Script de inicialização
    ports:
      - "5432:5432"  # Mapeando a porta do banco de dados
    networks:
      - plataforma-saas-network

  backend:
    build:
      context: ./backend
    container_name: plataforma-saas_backend
    environment:
      DATABASE_URL: postgres://saas:senha_segura@db:5432/plataforma
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - plataforma-saas-network
    command: ["sh", "-c", "sleep 10 && npm start"]


  frontend:
    build:
      context: ./frontend
    container_name: plataforma-saas_frontend
    ports:
      - "3001:3000"  # Mapeando a porta do frontend
    networks:
      - plataforma-saas-network

networks:
  plataforma-saas-network:
    driver: bridge
