version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: plataforma-saas_backend
    environment:
      DATABASE_URL: postgresql://saas:senha_segura@172.17.0.1:5432/plataforma
      NODE_ENV: development
      PORT: 3000
      JWT_SECRET: your_jwt_secret_key

    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "5555:5555"
    networks:
      - plataforma-saas-network
    entrypoint: ["./entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
    container_name: plataforma-saas_frontend
    ports:
      - "3002:3000"
    networks:
      - plataforma-saas-network
    volumes:
      - ./frontend:/app
    working_dir: /app

  videowall:
    build: ./videowall
    container_name: plataforma-saas_videowall
    restart: always
    volumes:
      - ./videowall:/app
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://saas:senha_segura@172.17.0.1:5432/plataforma
    networks:
      - plataforma-saas-network
    command: >
      bash -c "python wait_for_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  db_data:

networks:
  plataforma-saas-network:
    driver: bridge
